In [14]:
import os
interface_dir = os.environ["DATA"] + "webinterfaces/int03_prototype/"
user_data_dir = "functions/data/user-data"

In [15]:
path = "/home/jleguy/Téléchargements/user-data (1)/TESTCF1.json"

In [16]:
import json

def load_file(path):
    with open(path) as json_data:
        d = json.load(json_data)
        return d

expe_json_data = load_file(path)

In [35]:
import numpy as np

def extract_p_expe_results(d_p_expe):

    # Counting number of questions
    nb_quest = len(d_p_expe.keys())

    answers_vect = np.zeros((nb_quest,), dtype=float)
    time_vect = np.zeros((nb_quest,), dtype=float)
    time_exceeded_vect = np.zeros((nb_quest,), dtype=bool)

    for k, v in d_p_expe.items():
        if k == "time_on_page":
            continue
        curr_idx = v["order_index"]
        answers_vect[curr_idx] = v["answers"][0][0] if v["answers"][0] else None
        time_vect[curr_idx] = v["time"]
        time_exceeded_vect[curr_idx] = v["is_time_exceeded"]

    return answers_vect, time_vect, time_exceeded_vect

(array([ 0.,  1.,  0.,  1.,  1.,  1.,  0., nan,  1.,  1.,  0.]),
 array([4000., 4900., 3900., 5800.,  300., 4700., 5000., 7000., 4800.,
        5700.,    0.]),
 array([False, False, False, False, False, False, False,  True, False,
        False, False]))

{'task_0': {'answers': [[]],
  'time': 7000,
  'is_time_exceeded': True,
  'order_index': 7},
 'task_1': {'answers': [[1]],
  'time': 300,
  'is_time_exceeded': False,
  'order_index': 4},
 'task_2': {'answers': [[0]],
  'time': 5000,
  'is_time_exceeded': False,
  'order_index': 6},
 'task_3': {'answers': [[1]],
  'time': 5700,
  'is_time_exceeded': False,
  'order_index': 9},
 'task_4': {'answers': [[1]],
  'time': 4900,
  'is_time_exceeded': False,
  'order_index': 1},
 'task_5': {'answers': [[1]],
  'time': 4700,
  'is_time_exceeded': False,
  'order_index': 5},
 'task_6': {'answers': [[1]],
  'time': 5800,
  'is_time_exceeded': False,
  'order_index': 3},
 'task_7': {'answers': [[0]],
  'time': 3900,
  'is_time_exceeded': False,
  'order_index': 2},
 'task_8': {'answers': [[0]],
  'time': 4000,
  'is_time_exceeded': False,
  'order_index': 0},
 'task_9': {'answers': [[1]],
  'time': 4800,
  'is_time_exceeded': False,
  'order_index': 8},
 'time_on_page': 51440}